### ISSUE TITLE
Utilisation de cette intro

### ISSUE THREAD

**Issue by Grahack** [b2renger/Introduction_p5js#6]
Salut Bérenger,
C’est Christophe de MicroAlg.
À quelle occasion tu te sers de cette introduction ?

**Comment by b2renger** [comment]
Hello Christophe,

Je m'en sers pour un cours d'intro à la programmation à l'ECV c'est pour l'instant le seul endroit où j'ai  pu éprouver ce cours. Et encore on en est qu'au début :)

**Comment by Grahack** [comment]
K thx!
